services:
  devserver:
    image: dev:latest
    entrypoint: /bin/bash
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: C:/Users/${USERNAME}/linux
        target: /home/boulder/linux
      - type: bind
        source: ./ssh
        target: /home/boulder/.ssh
      - type: bind
        source: ./dotfiles/.aws
        target: /home/boulder/.aws
      - //var/run/docker.sock:/var/run/docker.sock
    user: "boulder:root"
