services:
  devserver:
    image: ${CONTAINER_NAME}:latest
    build:
      context: .
      args:
        - USER_NAME=${USER_NAME}
    entrypoint: /bin/bash
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: C:/Users/${USERNAME}/linux
        target: /home/${USER_NAME}/linux
      - type: bind
        source: ./ssh
        target: /home/${USER_NAME}/.ssh
      - type: bind
        source: ./dotfiles/.aws
        target: /home/${USER_NAME}/.aws
      - //var/run/docker.sock:/var/run/docker.sock
    user: "${USER_NAME}:root"
